# Generated by Django 4.1.2 on 2022-10-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=15, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('in_stock', models.BooleanField(default=True, verbose_name='En stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor de venta')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor de compra')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('count_registers', models.IntegerField(default=1, verbose_name='Cantidad de registros')),
                ('processsed', models.BooleanField(default=False, verbose_name='Carga procesada')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Ruta de archivo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_customers', to='inventario.customer')),
            ],
            options={
                'verbose_name': 'Archivo cargado',
                'verbose_name_plural': 'Archivos cargados',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_final', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='inventario.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='inventario.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventario.product')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
